Repository LostRuins/lite.koboldai.net, pull requests merged in 2024-12, with the labels that each got.

#96 Fix text wrap around avatars in Classic UI mode
  index.html
Labels: enhancement, good first issue

#98 AllTalk update Standard & Streaming generation
  index.html
Labels: enhancement, help wanted

#82 feature: Addition of memory snippets
  index.html
Labels: enhancement
